content_sources:
  lobby_test: {scene_asset: assets/lobby_cube.obj, type: lobby_scene}
  test_pattern: {file: assets/test_pattern.png, light_vignette: true, type: image}
projectors:
  main:
    display_index: 1
    resolution: [1920, 1080]
shows:
  lobby_show:
    loop: true
    scenes:
    - at: 0
      content_layers:
      - {source: lobby_test}
      surface: wall_main
  test_pattern_show:
    loop: true
    scenes:
    - at: 0
      content_layers:
      - {source: test_pattern}
      surface: wall_main
surfaces:
  wall_main:
    dst_quad_pixels:
    - [250, 212]
    - [1820, 100]
    - [1716, 892]
    - [100, 980]
    projector: main
    type: flat
