
projectors:
  main:
    display_index: 1
    resolution: [1920, 1080]

surfaces:
  wall_main:
    projector: main
    type: flat
    dst_quad_pixels: []

content_sources:
  test_pattern:
    type: image
    file: "assets/test_pattern.png"
    light_vignette: true

  depth_art:
    type: depth_image
    rgb: "assets/art_rgb.jpg"
    depth: "assets/art_depth.png"
  lobby_test:
    type: lobby_scene
    scene_asset: "assets/lobby_cube.obj"

shows:
  gallery_demo:
    loop: true
    scenes:
      - at: 0
        surface: wall_main
        content_layers:
          - source: test_pattern

  lobby_demo:
    loop: true
    scenes:
      - at: 0
        surface: wall_main
        content_layers:
          - source: lobby_test
